### PR TITLE
Update sk.yml

### PR DESCRIPTION
**Pull request by rasstislav**

### CODE REVIEW

**Comment by UndefinedOffset** [comment]
Any chance you have a [transifex](https://www.transifex.com/silverstripe/silverstripe-sortablegridfield/) account? Translations are managed through there, though I can definitely copy these changes over to it if you do not.

**Comment by rasstislav** [comment]
Yes, I have transifex account...

**Comment by UndefinedOffset** [comment]
Just want to keep it in sync ;) I know the SilverStripe team tries likes to keep them managed there since sortablegridfield is part of their common web platform thing. Let me know though if you have problems and I'll just copy it over myself. Appreciate it if you do end up doing it though ;)

**Comment by rasstislav** [comment]
Everything is done. Please sync it. Thanks!

**Comment by UndefinedOffset** [comment]
Thanks! I've committed the new translations

**Pull request closed without merging**
