### PR TITLE
WIP: SS4 Compatibility

### PR DESCRIPTION
**Pull request by zanderwar**
This PR is a compatibility upgrade to SilverStripe 4.x

#### Todo
- [x] Namespacing
- [x] Update all previously deprecated and/or now removed classes/functions
- [x] Ensure tests pass
  - [x] Update fixtures to use FQCN
- [x] Update README.md
- [x] Update composer.json
- [x] Update .travis.yml and .scrutinizer.yml
- [ ] Ensure examples are working
- [ ] Clean up display of the sortable grid header

### CODE REVIEW

**Comment by UndefinedOffset** [comment]
Watch when you squash this, I think if you include the first two commits in the squash you'll loose the history because too much will change and git will see it as a new file. Also before I merge this (which will be next week likely) I may start a 2.0.x branch or at least start with #103 and #102. The later brings code formatting inline with the core.

**Comment by zanderwar** [comment]
Correct, have been stung by the renames before hence the seperate commits purely for those reasons :)

**Comment by zanderwar** [comment]
I'd go for dropping that latter PR in favour of this just to reduce any concern of conflict

**Comment by zanderwar** [comment]
Squashed and passing @UndefinedOffset, you able to assist with the JS and ensuring the gridfield header is working correctly

Never used entwine so the porting would be quite difficult for me

**Comment by UndefinedOffset** [comment]
This is merged into the 2.0.x branch, not sure why this didn't auto marked merged, probably because I merged it to another branch

**Comment by zanderwar** [comment]
May have been the WIP. I know gitlab prevents it atleast

**Pull request closed without merging**
