### PR TITLE
Merge Experimental into master

### PR DESCRIPTION
**Pull request by nzphoenix**
This will allow users who are using Versioned dataobjects to receive the latest commits to master.

### CODE REVIEW

**Comment by UndefinedOffset** [comment]
I'm probably going to manually apply the changes needed, for one its conflicted and for another the branch is very out of date. Likely this merge will cause regressions, plus I think the changes could be done better. Let's leave this open though to remind me to actually do it ;)

**Comment by UndefinedOffset** [comment]
I keep forgetting about this, I'm going to try and take a stab at re-creating this today or tomorrow. I think re-creating it is probably the best bet at this point given how out of sync the branches are and as I say above I think it could be done differently.

**Comment by UndefinedOffset** [comment]
I've got a change in master that seems to work well, I want to expand the unit tests to cover (#88) before I call it done and tag it. Plus I want to do some more testing on it.

**Comment by UndefinedOffset** [comment]
I'm going to close this, lets open an issue if there is still more needed for this, master's 10a52463f47af2f705cd2c215283be06ed4b20c9 should have added support for this

**Comment by adamjudd** [comment]
@UndefinedOffset - Thanks, works great!

**Pull request closed without merging**
