### PR TITLE
DOC Note that module is not compatible with CMS5

### PR DESCRIPTION
**Pull request by sabina-talipova**
## Parent issue
- https://github.com/silverstripe/.github/issues/25

### CODE REVIEW

**Comment by UndefinedOffset** [comment]
In my own testing and in the composer.json file this is not true. While it is not commercially supported by the Silverstripe team anymore it does appear to be working fine. Have you verified that it is indeed not functional in Silverstripe 5? If so are their errors accordingly.

**Comment by maxime-rainville** [comment]
@UndefinedOffset I created a card about removing CMS 5 branches from modules that don't have commercial support. I wasn't specific to say that this should only apply to modules owned by Silverstripe. Sorry for the confusion.

This PR can probably be closed.

**Comment by UndefinedOffset** [comment]
All good though I have made a note to remove the Silverstripe supported badge ;)

**Comment by sabina-talipova** [comment]
@UndefinedOffset, sorry for confused PR. We will update our docs and change status from "Dropped" to "CMS5 compatible without commercial support". 
Thank you for your update.

**Pull request closed without merging**
