### PR TITLE
Fixing bug "must be an Int, column is of type int"

### PR DESCRIPTION
**Pull request by spekulatius**
Hello @UndefinedOffset 

I run into this error: *'Sort column SortOrder must be an Int, column is of type int'*. My dataobject has this $db:

    private static $db = array(
        'SortOrder' => 'int'
    );

which works fine - just the validation in GridFieldSortableRows.php is a bit to tough. I adjusted this. Let me know if you want to merge this in. 

Spek

### CODE REVIEW

**Comment by spekulatius** [comment]
It might be easier to review a version without whitespace changes: https://github.com/UndefinedOffset/SortableGridField/pull/79/files?w=1

**Comment by UndefinedOffset** [comment]
While I agree this patch is ok and probably a good workaround to PHP's case insensitivity in regards to method, variable and class names etc. The "Int" class in SilverStripe is actually "[Int](http://api.silverstripe.org/3.2/class-Int.html)" with the uppercase "I". I'll merge this patch later the white space changes will require a manual merge I think.

**Comment by spekulatius** [comment]
The merge should work - doesn't look like its raising any conflicts. It would be great if you could tag a release so I don't have to fix my composer.json to a particular hash.

**Comment by UndefinedOffset** [comment]
I've merged this, and tagged 0.5.3. Thanks :)

**Comment by spekulatius** [comment]
thank you :)

**Pull request closed without merging**
